import Head from "next/head";
import Input from "../components/form/Input";
import Home from "./Home";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";

export default function Index() {
  return (
    <div className="">
      <Head>
        <title>LGR Mermer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
    </div>
  );
}
